[versions]
caffeineVersion = "3.1.8"
jdaVersion = "5.1.0"
jsoupVersion = "1.18.3"
junitJupiterVersion = "6.0.1"
jwizardLibVersion = "latest"
kotlinVersion = "2.2.0"
logbackVersion = "1.5.20"
shadowJarVersion = "8.1.8"
springVersion = "6.2.12"

[libraries]
caffeine = { module = "com.github.ben-manes.caffeine:caffeine", version.ref = "caffeineVersion" }
jda = { module = "net.dv8tion:JDA", version.ref = "jdaVersion" }
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoupVersion" }
junitJupiter = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junitJupiterVersion" }
junitJupiterEngine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junitJupiterVersion" }
junitPlatformLauncher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junitJupiterVersion" }
jwizardLib = { module = "pl.jwizard:jwizard-lib", version.ref = "jwizardLibVersion" }
kotlin = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlinVersion" }
kotlinReflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlinVersion" }
logbackClassic = { module = "ch.qos.logback:logback-classic", version.ref = "logbackVersion" }
springContextSupport = { module = "org.springframework:spring-context-support", version.ref = "springVersion" }

[plugins]
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlinVersion" }
kotlinSpring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlinVersion" }
shadowJar = { id = "io.github.goooler.shadow", version.ref = "shadowJarVersion" }
